#!/bin/bash
# Quick Reference: 6-Hour Session Monitoring Commands
# ====================================================
# Run these commands from the terminal to monitor the trading session

echo "🎯 6-HOUR SESSION QUICK REFERENCE"
echo "=================================="
echo ""
echo "📊 MONITORING COMMANDS:"
echo ""
echo "1️⃣  View Real-Time Checkpoints:"
echo "   tail -f 6HOUR_SESSION_MONITOR.log | grep CHECKPOINT"
echo ""
echo "2️⃣  View Last 50 Lines of Log:"
echo "   tail -50 6HOUR_SESSION_MONITOR.log"
echo ""
echo "3️⃣  Watch for Errors:"
echo "   tail -f 6HOUR_SESSION_MONITOR.log | grep -E 'ERROR|CRASH|WARNING'"
echo ""
echo "4️⃣  Check Process Status:"
echo "   ps aux | grep -E 'MASTER_SYSTEM|RUN_6HOUR' | grep -v grep"
echo ""
echo "5️⃣  Get Process Details:"
echo "   ps -p 88999 -o pid,user,%cpu,%mem,comm"
echo ""
echo "6️⃣  View Session Timeline:"
echo "   grep -E 'CHECKPOINT|Started|completed' 6HOUR_SESSION_MONITOR.log"
echo ""
echo "7️⃣  Count How Many Checkpoints Completed:"
echo "   grep 'CHECKPOINT.*1/12\\|CHECKPOINT.*2/12\\|CHECKPOINT.*3/12' 6HOUR_SESSION_MONITOR.log | wc -l"
echo ""
echo "💾 LOG FILES:"
echo ""
echo "- Main Session Log: 6HOUR_SESSION_MONITOR.log"
echo "- Final Report: 6HOUR_SESSION_REPORT.md"
echo ""
echo "🛑 STOP COMMANDS (if needed):"
echo ""
echo "  # Graceful stop"
echo "  pkill -f RUN_6HOUR_SESSION.py"
echo ""
echo "  # Force stop everything"
echo "  pkill -9 -f 'MASTER_SYSTEM\\|RUN_6HOUR'"
echo ""
echo "🔄 RESTART COMMANDS (if needed):"
echo ""
echo "  cd /Users/mauf/Desktop/Octi\\ AI\\ Trading\\ Bot/octivault_trader"
echo "  nohup python3 RUN_6HOUR_SESSION.py > 6HOUR_SESSION_MONITOR.log 2>&1 &"
echo ""
echo "📈 WHAT TO EXPECT:"
echo ""
echo "✓ Checkpoint every 30 minutes"
echo "✓ CPU: 5-20% idle, peaks during trades"
echo "✓ Memory: 200-400 MB"
echo "✓ First trades: After 30-60 minutes"
echo "✓ No crashes (if any, auto-recovery up to 3x)"
echo ""
echo "=================================="
echo "Session Running: PID 88999 (Trading System), PID 88937 (Monitor)"
echo "Expected Completion: 2026-04-24 07:49:00 EET (+6 hours)"
echo "=================================="
